# Site settings
title: Alison O. Gaby - Workings
email: aogaby5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/index.html" # the subpath of your site, e.g. /blog/
url: "http://aog5.github.io" # the base hostname & protocol for your site
twitter_username: AliGaby23
github_username:  aog5

# Build settings
markdown: kramdown
